dist: xenial

sudo: required

language: java

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/pip
    - $HOME/downloads

branches:
  only:
    - master
    - /^release-.*$/
    - /^test-.*$/


### 搭建python 3.7环境
before_install:
  # 安装python环境
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get -q update
  - sudo apt-get -y install python3.7
  # 修改python版本的使用优先级
  - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 1
  - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2
  # 修改python默认使用的版本
  - sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 100
  - sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 150
  
### 安装相关依赖
install:
  - sudo apt-get -y install python3-pip
  - sudo pip3 install -r ./requirements.txt 
#   - sudo pip3 install codecov

addons:
  apt:
    packages:
      - lynx

### 获取graph测试服务
before_script:
  - sudo python src/deploy_start.py all

### 执行测试脚本
script:
  - sudo pytest src/test_start.py -m 'caseL0' -s --html=test.html --capture=tee-sys
  
after_success:
  - sudo lynx -dump home/travis/build/hugegraph/hugegraph-test/test.html
#   - codecov
        
