language: java

jdk:
  - openjdk8

dist: xenial

sudo: required

cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/pip
    - $HOME/downloads

branches:
  only:
    - master
    - /^integration-.*$/
    - /^individual-.*$/
    - ci_test
 
before_install:
    - java -version
    - python3 --version

# ### 搭建python 3.7.6环境
# before_install:
#   - python --version
#   - sudo add-apt-repository -y ppa:jonathonf/python-3.7
#   - sudo apt-get -q update
#   - sudo apt-get -y install python-3.7
#   - python --version
  
# ### 安装相关依赖
# install:
#   - pwd

# ### 获取graph测试服务
# before_script:
#   - cd tempTest
#   - python testGraph/deploy_start.py all

# ### 执行测试脚本
# script:
#   - pytest testGraph/test_start.py -m 'caseL0' -s --html=test.html --capture=tee-sys


job:
  include:
    - language: python
      ptthon: 3.7.6
      
      install:
        - pwd
        - java -version
        - python3 --version
      
      before_script:
        - cd tempTest
        - ls
        - python testGraph/deploy_start.py all
          
      script:
        - pytest testGraph/test_start.py -m 'caseL0' -s --html=test.html --capture=tee-sys
