language: java

jdk:
  - oraclejdk8

dist: trusty

sudo: required

cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/pip
    - $HOME/downloads

### 过滤自动化构建的分支
branches:
  only:
    - master
    - /^integration-.*$/
    - /^individual-.*$/
    - ci_test


### 搭建python 3.7.6环境；并安装相关依赖
install:
  - pwd
  - java -version
  - python --version

### 获取graph测试服务
before_script:
  - python testGraph/deploy_start.py all
    
### 执行测试脚本
script:
  - pytest testGraph/test_start.py -m 'caseL0' -s --html=test.html --capture=tee-sys
