dist: xenial

language: java

jdk:
  - oraclejdk8

dist: trusty

sudo: required

cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/pip
    - $HOME/downloads

branches:
  only:
    - master
    - /^integration-.*$/
    - /^individual-.*$/
    - ci_test

job:
  include:
    - language: python
      ptthon: 3.7.6
      
      install:
        - pwd
        - java -version
        - python --version
      
      before_script:
        - cd tempTest
        - ls
        - python testGraph/deploy_start.py all
          
      script:
        - pytest testGraph/test_start.py -m 'caseL0' -s --html=test.html --capture=tee-sys
