dist: xenial

sudo: required

language: java

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/pip
    - $HOME/downloads

branches:
  only:
    - master
    - /^integration-.*$/
    - /^individual-.*$/
    - ci_test

### 搭建python 3.7.6环境
before_install:
  - pwd
  - java -version
  - python3 --version
  
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get -q update
  - sudo apt search python3.7
  - sudo apt-get -y install python3.7.6
  
  - python3 --version
  
# ### 安装相关依赖
# install:
#   - pwd
#   - java -version
#   - python3 --version

# ### 获取graph测试服务
# before_script:
#   - python testGraph/deploy_start.py all

# ### 执行测试脚本
# script:
#   - pytest testGraph/test_start.py -m 'caseL0' -s --html=test.html --capture=tee-sys



        
        
        
        
