name: hugegraph code statistics
on:
  pull_request:
    branches:
      - master
  # 每月的1号在8点执行任务
  schedule:
    - cron: '0 0 1 * *'
  # 手动触发
  workflow_dispatch:

# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     # Map a step output to a job output
#     outputs:
#       output1: ${{ steps.step1.outputs.test }}
#       output2: ${{ steps.step2.outputs.test }}
#     steps:
#     - id: step1
#       run: echo "::set-output name=test::hello"
#     - id: step2
#       run: echo "::set-output name=test::world"
#   job2:
#     runs-on: ubuntu-latest
#     needs: job1
#     steps:
#     - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}


jobs:
 server_repository:
   runs-on: ubuntu-16.04
   outputs:
     add: ${{ steps.server_stat.outputs.add }}
     sub: ${{ steps.server_stat.outputs.sub }}
     loc: ${{ steps.server_stat.outputs.loc }}
   steps:
     - id: server_stat
       run: |
         git clone https://github.com/hugegraph/hugegraph.git
         ls
         pwd
         cd hugegraph
         git log  --all --pretty=tformat: --since=2021-06-01 --until=2021-07-01  --numstat | awk '{ add += $1; sub += $2; loc += $1 - $2 } END { printf "%s, %s, %s", add, sub, loc }'

#git log  --all --pretty=tformat: --since=2021-06-01 --until=2021-07-01  --numstat | awk '{ add += $1; sub += $2; loc += $1 - $2 } END { printf "::set-output name=add::%s, ::set-output name=sub::%s, ::set-output name=loc::%s", add, sub, loc }'


 loader_repository:
   runs-on: ubuntu-16.04
   needs: server_repository
   outputs:
     add: ${{ steps.loader_stat.outputs.add }}
     sub: ${{ steps.loader_stat.outputs.sub }}
     loc: ${{ steps.loader_stat.outputs.loc }}
   steps:
     - id: loader_stat
       run: |
         echo ${{needs.server_repository.outputs.add}} ${{needs.server_repository.outputs.sub}} ${{needs.server_repository.outputs.loc}} 
         git clone git@github.com:hugegraph/hugegraph.git
         git log  --all --pretty=tformat: --since=2021-06-01 --until=2021-07-01  --numstat | awk '{ add += $1; subs += $2; loc += $1 - $2 } END { printf "added lines: %s, removed lines: %s, total lines: %s\n", add, subs, loc }'

