name: hugegraph code statistics
on:
  pull_request:
    branches:
      - master
  # 每月的1号在8点执行任务
  schedule:
    - cron: '0 0 1 * *'
  # 手动触发
  workflow_dispatch:

jobs:
 server_repository:
   runs-on: ubuntu-16.04
#    outputs:
#      add: ${{ steps.server_stat.outputs.add }}
#      sub: ${{ steps.server_stat.outputs.subs }}
   steps:
     - id: server_stat
       run: |
         git clone https://github.com/hugegraph/hugegraph.git
         cd hugegraph
         git log  --all --pretty=tformat: --since=2021-06-01 --until=2021-07-01  --numstat | awk '{ add += $1; subs += $2; loc += $1 + $2 } END { printf "::set-output name=add::%s", add; printf "::set-output name=subs::%s", subs}'
#         git log  --all --pretty=tformat: --since=2021-06-01 --until=2021-07-01  --numstat | awk '{ add += $1; subs += $2; loc += $1 + $2 } END { printf "::set-output name=subs::%s", subs}'
     - id: test
       run: |
         echo ${{steps.server_stat.outputs.add}}
         echo ${{steps.server_stat.outputs.subs}}
  
#  loader_repository:
#    runs-on: ubuntu-16.04
#    needs: server_repository
# #    outputs:
# #      add: ${{ steps.loader_stat.outputs.add }}
# #      sub: ${{ steps.loader_stat.outputs.subs }}
# #      loc: ${{ steps.loader_stat.outputs.loc }}
#    steps:
#      - id: loader_stat
#        run: |
#          echo '${{needs.server_repository.outputs.add}}, ${{needs.server_repository.outputs.sub}}, ${{needs.server_repository.outputs.loc}}'
#          git clone https://github.com/hugegraph/hugegraph-loader.git
#          cd hugegraph-loader
#          git log  --all --pretty=tformat: --since=2021-06-01 --until=2021-07-01  --numstat | awk '{ add += $1; subs += $2; loc += $1 + $2 } END { printf "added lines: %s, removed lines: %s, total lines: %s\n", add + ${{needs.server_repository.outputs.add}}, subs + ${{needs.server_repository.outputs.sub}}, loc + ${{needs.server_repository.outputs.loc}}}'
        
