name: hugegraph code statistics
on:
  pull_request:
    branches:
      - master
  # 每月的1号在8点执行任务
  schedule:
    - cron: '0 0 1 * *'
  # 手动触发
  workflow_dispatch:


jobs:
 code_statistics:
   runs-on: ubuntu-16.04
   steps:
      - uses: actions/checkout@v2
        with:
          repository: hugegraph/hugegraph
#           token: ${{ secrets.ACCESS_TOKEN }}
      - id: test
        run: |
          ls
          pwd

          

#      - id: server_stat
#        run: |
#          git clone https://github.com/hugegraph/hugegraph.git
#          cd hugegraph
#          git log  --all --pretty=tformat: --since=2021-06-01 --until=2021-07-01  --numstat | awk '{ add += $1; subs += $2} END { printf "%s,%s\n", add, subs }' >> ../stat.txt
     
#      - id: loader_stat
#        run: |
#          git clone https://github.com/hugegraph/hugegraph-loader.git
#          cd hugegraph-loader
#          git log  --all --pretty=tformat: --since=2021-06-01 --until=2021-07-01  --numstat | awk '{ add += $1; subs += $2} END { printf "%s,%s\n", add, subs }' >> ../stat.txt
     
#      - id: tools_stat
#        run: |
#          git clone https://github.com/hugegraph/hugegraph-tools.git
#          cd hugegraph-tools
#          git log --all --pretty=tformat: --since=2021-06-01 --until=2021-07-01  --numstat | awk '{ add += $1; subs += $2} END { printf "%s,%s\n", add, subs }' >> ../stat.txt
     
#      - id: hubbble_stat
#        run: |
#          git clone https://github.com/hugegraph/hugegraph-hubble.git
#          cd hugegraph-hubble
#          git log  --all --pretty=tformat: --since=2021-06-01 --until=2021-07-01  --numstat | awk '{ add += $1; subs += $2} END { printf "%s,%s\n", add, subs }' >> ../stat.txt
#          cat ../stat.txt
     
#      - id: stat1
#        run: |
#          mkdir ee && cd ee
#          ls
#          git clone git@github.com:hugegraph-ee/hugegraph.git
#          cd hugegraph
#          git log --all --pretty=tformat: --since=2021-06-01 --until=2021-07-01  --numstat | awk '{ add += $1; subs += $2} END { printf "%s,%s\n", add, subs }' >> ../stat.txt       
#          cat ../stat.txt
         
#      - id: stat2
#        run: |
#          cd ee
#          git clone https://github.com/hugegraph-ee/hugegraph-signature.git
#          cd hugegraph-signature
#          git log --all --pretty=tformat: --since=2021-06-01 --until=2021-07-01  --numstat | awk '{ add += $1; subs += $2} END { printf "%s,%s\n", add, subs }' >> ../stat.txt       
#          cat ../stat.txt
         
